# remap prefix from 'C-b' to 'C-a'
#unbind C-b
#set-option -g prefix C-a

# switch to last window like screen, by holding down Control
bind C-b last-window
bind b send-prefix

# open command prompt with ;
unbind \;
bind \; command-prompt

# split panes using | and -
#unbind '"'
#unbind %
bind | split-window -h
bind - split-window -v

# reload config file with r
bind r source-file ~/.tmux.conf \; display ".tmux.conf reloaded!"

# switch panes using Vim navigation keys
unbind l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
